const M="telynors-elemental-reactions";
const E=[["fire","Fire","#ff6a2a"],["ice","Ice","#74e8ff"],["nature","Nature","#62df72"],["wind","Wind","#75e8cf"],["light","Light","#ffe866"],["dark","Dark","#9d68e8"],["physical","Physical","#d9d9d9"]].map(([id,name,color])=>({id,name,color,icon:"icons/svg/aura.svg"}));
const P=[["fire","ice","Frostburn"],["fire","nature","Enkindle"],["fire","wind","Vortex"],["fire","light","Sunshield"],["fire","dark","Sunder"],["ice","nature","Rimebud"],["ice","wind","Vortex"],["ice","light","Ice Aegis"],["ice","dark","Blizzard"],["nature","wind","Vortex"],["nature","light","Spriteshield"],["nature","dark","Prana"],["wind","light","Vortex"],["wind","dark","Vortex"],["light","dark","Annihilate"]];
const R=P.map(([a,b,name])=>({id:a+"-"+b,elements:[a,b],name,effects:[],text:{mode:"gradient",direction:"right"}}));
const get=k=>game.settings.get(M,k), cp=x=>foundry.utils.deepClone(x), el=id=>get("elements").find(x=>x.id===id), key=(a,b)=>[a,b].sort().join("|");
function reaction(a,b){return get("reactions").find(r=>key(...r.elements)===key(a,b))}
function active(a){return a?.getFlag(M,"activeElement")} function applied(t){return t?.document?.getFlag(M,"appliedElement")}
async function setElement(t,id,source){if(!t||!el(id))return;let old=applied(t);if(old&&old!==id){let r=reaction(old,id);if(r){await runReaction(r,{sourceActor:source,targetToken:t,firstElement:old,secondElement:id});await t.document.unsetFlag(M,"appliedElement");return refresh(t)}}await t.document.setFlag(M,"appliedElement",id);await refresh(t)}
async function damage(actor,t,formula,type){if(!formula)return;let roll=await new Roll(formula,actor?.getRollData?.()||{}).evaluate();if(game.dice3d)try{await game.dice3d.showForRoll(roll,game.user,true)}catch{};if(globalThis.MidiQOL?.applyTokenDamage)await MidiQOL.applyTokenDamage([{damage:roll.total,type,properties:new Set()}],roll.total,new Set([t]),null,null);else{let hp=t.actor.system.attributes.hp;await t.actor.update({"system.attributes.hp.value":Math.max(0,hp.value-roll.total)})}}
async function runEffect(f,c){if(f.type==="damage"){await damage(c.sourceActor,c.targetToken,f.formula,f.damageType||f.elementId);return[c.targetToken]}if(f.type==="applyElement"){await setElement(c.targetToken,f.elementId||c.secondElement,c.sourceActor);return[c.targetToken]}if(f.type==="summon"&&f.actorUuid){let a=await fromUuid(f.actorUuid);if(!a)return[];let td=await a.getTokenDocument({x:c.targetToken.document.x+20,y:c.targetToken.document.y+20});let[d]=await canvas.scene.createEmbeddedDocuments("Token",[td.toObject()]);await d.setFlag(M,"summoned",{elementId:f.elementId||c.secondElement,lifetime:f.lifetime||2});await summonedTurn();return[d.object]}if(f.type==="zone"){let e=f.elementId||c.secondElement;await canvas.scene.createEmbeddedDocuments("MeasuredTemplate",[{t:"circle",user:game.user.id,x:c.targetToken.center.x,y:c.targetToken.center.y,distance:Number(f.radius)||10,fillColor:el(e)?.color,flags:{[M]:{zone:{...f,elementId:e,sourceActorUuid:c.sourceActor?.uuid,damaged:[]}}}}]);await summonedTurn();return[c.targetToken]}return[c.targetToken]}
async function runReaction(r,c){let hit=new Set([c.targetToken]);for(let f of r.effects||[])for(let t of await runEffect(f,c)||[])hit.add(t);for(let t of hit)callout(t,r,c);Hooks.callAll(M+".reaction",{reaction:r,...c,affected:[...hit]})}
function layer(){let d=document.querySelector("#ter-callout-layer");if(!d){d=document.createElement("div");d.id="ter-callout-layer";document.body.append(d)}return d}
function callout(t,r,c){if(!t?.center)return;let a=el(r.name==="Vortex"?"wind":c.firstElement),b=el(c.secondElement),p=canvas.stage.worldTransform.apply(new PIXI.Point(t.center.x,t.center.y-t.h*.25)),d=document.createElement("div");d.className="ter-reaction-callout ter-gradient";d.textContent=(r.name==="Vortex"?"VORTEX":r.name).toUpperCase();d.style.left=p.x+"px";d.style.top=p.y+"px";d.style.backgroundImage=`linear-gradient(90deg,${a?.color||"#fff"},${b?.color||"#fff"})`;layer().append(d);setTimeout(()=>d.remove(),1600)}
async function refresh(t){if(!t)return;let e=el(applied(t));if(t._terBadge){t._terBadge.destroy();t._terBadge=null}if(t._terGlow){t.removeChild(t._terGlow);t._terGlow.destroy();t._terGlow=null}if(!e)return;let g=new PIXI.Graphics().circle(t.w/2,t.h/2,Math.max(t.w,t.h)*.55).stroke({width:5,color:PIXI.Color.shared.setValue(e.color).toNumber(),alpha:.7});t.addChildAt(g,0);t._terGlow=g;let tex=await loadTexture(e.icon);let s=Math.max(18,Math.min(t.w,t.h)*.24),b=new PIXI.Sprite(tex);b.width=b.height=s;b.x=2;b.y=t.h-s-2;t.addChild(b);t._terBadge=b}
async function summonedTurn(){if(!game.combat||!game.user.isGM||game.combat.combatants.some(c=>c.getFlag(M,"collective")))return;await game.combat.createEmbeddedDocuments("Combatant",[{name:"Summoned Entities",initiative:0,flags:{[M]:{collective:true}}}])}
async function zones(){for(let d of canvas.scene.templates){let z=d.getFlag(M,"zone");if(!z||!d.object?.shape)continue;let done=new Set(z.damaged||[]),src=z.sourceActorUuid?await fromUuid(z.sourceActorUuid):null;for(let t of canvas.tokens.placeables){let p=d.object.toLocal(t.center);if(!d.object.shape.contains(p.x,p.y))continue;if(z.damageFormula&&!done.has(t.document.uuid)){await damage(src,t,z.damageFormula,z.damageType||z.elementId);done.add(t.document.uuid)}await setElement(t,z.elementId,src)}await d.setFlag(M,"zone",{...z,damaged:[...done]})}}
class Manager extends foundry.applications.api.HandlebarsApplicationMixin(foundry.applications.api.ApplicationV2){static DEFAULT_OPTIONS={id:"ter-manager",window:{title:"Elemental Reactions",resizable:true},position:{width:860,height:720}};static PARTS={main:{template:`modules/${M}/templates/manager.hbs`}};async _prepareContext(){return{elements:cp(get("elements")),reactions:cp(get("reactions")),variants:cp(get("variants"))}}_onRender(){this.element.querySelector("[data-action='add-element']")?.addEventListener("click",async()=>{let n=prompt("Element name");if(!n)return;let a=cp(get("elements"));a.push({id:n.slugify({strict:true}),name:n,color:"#ffffff",icon:"icons/svg/aura.svg"});await game.settings.set(M,"elements",a);this.render()});this.element.querySelector("[data-action='add-reaction']")?.addEventListener("click",()=>new Wizard().render(true));this.element.querySelector("[data-action='add-variant']")?.addEventListener("click",async()=>{let n=prompt("Variant name");if(!n)return;let a=cp(get("variants"));a.push({id:n.slugify({strict:true}),name:n,priority:(a.length+1)*10,enabled:true,overrides:[]});await game.settings.set(M,"variants",a);this.render()});this.element.querySelector("[data-action='export']")?.addEventListener("click",()=>saveDataToFile(JSON.stringify({elements:get("elements"),reactions:get("reactions"),variants:get("variants")},null,2),"application/json","elemental-reactions.json"))}}
class Wizard extends foundry.applications.api.HandlebarsApplicationMixin(foundry.applications.api.ApplicationV2){static DEFAULT_OPTIONS={id:"ter-wizard",window:{title:"Reaction Creation Wizard",resizable:true},position:{width:720,height:760}};static PARTS={main:{template:`modules/${M}/templates/reaction-wizard.hbs`}};async _prepareContext(){return{elements:cp(get("elements"))}}_onRender(){let q=s=>this.element.querySelector(s),preview=q(".ter-preview"),paint=()=>{let a=el(q("[name=a]").value),b=el(q("[name=b]").value);preview.textContent=(q("[name=name]").value||"REACTION").toUpperCase();preview.style.backgroundImage=`linear-gradient(90deg,${a?.color},${b?.color})`};this.element.querySelectorAll("input,select").forEach(x=>x.addEventListener("input",paint));paint();q("[data-action=actor-drop]")?.addEventListener("drop",e=>{e.preventDefault();let d=TextEditor.getDragEventData(e);if(d.type==="Actor")q("[name=actorUuid]").value=d.uuid});q("[data-action=save]")?.addEventListener("click",async()=>{let f=new FormData(this.element),a=f.get("a"),b=f.get("b"),name=String(f.get("name")||"").trim();if(!name||a===b)return ui.notifications.warn("Choose two different elements and a name.");let effects=[],formula=String(f.get("formula")||"").trim(),uuid=String(f.get("actorUuid")||"").trim();if(formula)effects.push({type:"damage",elementId:f.get("damageElement"),formula,damageType:f.get("damageType")});if(uuid)effects.push({type:"summon",actorUuid:uuid,quantity:Number(f.get("quantity")||1),lifetime:Number(f.get("lifetime")||2),elementId:b});if(f.get("zone"))effects.push({type:"zone",radius:Number(f.get("radius")||10),elementId:b,damageFormula:String(f.get("zoneDamage")||""),damageType:String(f.get("zoneDamageType")||"")});let arr=cp(get("reactions")),r={id:a+"-"+b+"-"+name.slugify({strict:true}),elements:[a,b],name,effects,text:{mode:f.get("textMode"),direction:f.get("direction")}},i=arr.findIndex(x=>key(...x.elements)===key(a,b));i<0?arr.push(r):arr[i]=r;await game.settings.set(M,"reactions",arr);this.close()})}}
Hooks.once("init",()=>{for(let[k,d]of[["elements",E],["reactions",R],["variants",[]]])game.settings.register(M,k,{scope:"world",config:false,type:Object,default:d});game.settings.registerMenu(M,"manager",{name:"Elemental Reactions Manager",label:"Open Manager",icon:"fa-solid fa-atom",type:Manager,restricted:true})});
Hooks.once("ready",()=>{layer();game.modules.get(M).api={applyElement:setElement,executeReaction:runReaction,getElement:el,getReaction:reaction,showReactionText:callout,openManager:()=>new Manager().render(true)}});
Hooks.on("canvasReady",()=>canvas.tokens.placeables.forEach(refresh));Hooks.on("updateToken",(d,c)=>{if(foundry.utils.hasProperty(c,`flags.${M}.appliedElement`))refresh(d.object)});
Hooks.on("midi-qol.RollComplete",async w=>{if(!game.user.isGM)return;let e=active(w.actor);if(!e)return;for(let t of w.hitTargets||[])await setElement(t,e,w.actor)});
Hooks.on("updateCombat",async(c,x)=>{if(x.turn!==undefined&&c.combatant?.getFlag(M,"collective"))await zones()});
Hooks.on("renderActorSheet",(app,html)=>{let a=app.actor;if(a?.type!=="character")return;let root=html instanceof HTMLElement?html:html[0],old=root.querySelector(".ter-sheet-picker");if(old)return;let unlocked=a.getFlag(M,"unlockedElements")||[],allowed=game.user.isGM?get("elements"):get("elements").filter(e=>unlocked.includes(e.id)),d=document.createElement("div");d.className="ter-sheet-picker";d.innerHTML=`<label>Element</label><select>${allowed.map(e=>`<option value="${e.id}" ${active(a)===e.id?"selected":""}>${e.name}</option>`).join("")}</select>${game.user.isGM?'<button type="button" data-unlock>Unlocks</button>':""}`;d.querySelector("select").onchange=e=>a.setFlag(M,"activeElement",e.target.value);d.querySelector("[data-unlock]")?.addEventListener("click",async()=>{let names=get("elements").map(e=>e.name+" ("+e.id+")").join(", ");let s=prompt("Unlocked element IDs, comma separated. Available: "+names,unlocked.join(","));if(s!==null)await a.setFlag(M,"unlockedElements",s.split(",").map(x=>x.trim()).filter(Boolean))});(root.querySelector(".window-content")||root).prepend(d)});
